In [1]:
!pip install jovian

In [2]:
import jovian


## Exploring PyTorch Tensor Operations

In this notebook, we will cover the following PyTorch tensor functions:

- torch.zeros()
- torch.ones()
- torch.arange()
- torch.linspace()
- torch.eye()

We will illustrate their usage with code examples and provide explanations of each function

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [9]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros()

torch.zeros() - creates a new tensor filled with zeros. It takes the shape of the desired tensor as input and returns a tensor of the same shape with all elements set to zero. This function is useful for initializing tensors before performing computations. The data type of the tensor can be specified using the dtype parameter.




##Example1

In [10]:
# a 2x3 tensor filled with zeros
zeros_tensor = torch.zeros(2, 3)
print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


##Example2

In [11]:
 #a 2x2x2 tensor filled with zeros of data type long (int64)
zeros_tensor2 = torch.zeros((2, 2, 2), dtype=torch.long)
print(zeros_tensor2)

tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]])


##Example 3

In [13]:
#  a 5x4 tensor filled with zeros
zeros_tensor1 = torch.zeros(5, 4)
print(zeros_tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


## Function 2 - torch.ones():

torch.ones() creates a new tensor filled with ones. It takes the shape of the desired tensor as input and returns a tensor of the same shape with all elements set to one. This function is useful for initializing tensors with default values.

##Example1

In [14]:
# a 3x2 tensor filled with ones
ones_tensor = torch.ones(3, 2)
print(ones_tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


##Example2

In [15]:
# a 4x6 tensor filled with ones
ones_tensor1 = torch.ones(4, 6)
print(ones_tensor1)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


##Example3

In [16]:
#  a 2x3 tensor filled with ones of data type float (float32)
ones_tensor2 = torch.ones((2, 3), dtype=torch.float)
print(ones_tensor2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


## Function 3 - torch.arange():

torch.arange() returns a 1-D tensor with values from start to end-1 with a step size of step. It is similar to the Python built-in range() function, but it returns a tensor instead of a list. This function is useful for creating a sequence of numbers within a specific range.

##Example1

In [4]:
# a tensor with values from 0 to 9
range_tensor = torch.arange(10)
print(range_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


##Example2

In [17]:
# a tensor with values from 5 to 15 (exclusive)
range_tensor1 = torch.arange(5, 15)
print(range_tensor1)

tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


##Example3

In [18]:
#  a tensor with values from -5 to 5 (exclusive) with a step of 2
range_tensor2 = torch.arange(-5, 5, 2)
print(range_tensor2)

tensor([-5, -3, -1,  1,  3])


## Function 4 - torch.linspace():

torch.linspace() returns a 1-D tensor with steps equally spaced values between start and end (inclusive). Unlike torch.arange(), you specify the number of steps rather than the step size. This function is useful when you need a fixed number of values within a range.

##Example1

In [5]:
# a tensor with 5 equally spaced values between 0 and 1
linspace_tensor = torch.linspace(0, 1, 5)
print(linspace_tensor)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


##Example2

In [19]:
# a tensor with 6 equally spaced values between 0 and 2 (inclusive)
linspace_tensor1 = torch.linspace(0, 2, 6)
print(linspace_tensor1)

tensor([0.0000, 0.4000, 0.8000, 1.2000, 1.6000, 2.0000])


##Example3

In [20]:
# a tensor with 9 equally spaced values between -1 and 1 (inclusive)
linspace_tensor2 = torch.linspace(-1, 1, 9)
print(linspace_tensor2)

tensor([-1.0000, -0.7500, -0.5000, -0.2500,  0.0000,  0.2500,  0.5000,  0.7500,
         1.0000])


## Function 5 - torch.eye():

torch.eye() creates an identity tensor of size n x n, where the diagonal elements are ones, and all other elements are zeros. This function is particularly useful for creating identity matrices which are often used in linear algebra operations.

##Example1

In [6]:
# a 3x3 identity matrix
identity_tensor = torch.eye(3)
print(identity_tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


##Example2

In [21]:
# a 5x5 identity matrix
identity_tensor1 = torch.eye(5)
print(identity_tensor1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


##Example3

In [22]:
# a 2x2 identity matrix of data type integer (int64)
identity_tensor2 = torch.eye(2, dtype=torch.int64)
print(identity_tensor2)

tensor([[1, 0],
        [0, 1]])


Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [4]:
!pip install jovian --upgrade --quiet

In [5]:
import jovian

In [23]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Conclusion

In this notebook, we explored five important PyTorch tensor functions: torch.zeros(), torch.ones(), torch.arange(), torch.linspace(), and torch.eye(). Here's a brief summary of what we covered:

torch.zeros(): Used for creating tensors filled with zeros. It takes the shape of the desired tensor as input and returns a tensor of the same shape with all elements set to zero.

torch.ones(): Used for creating tensors filled with ones. It takes the shape of the desired tensor as input and returns a tensor of the same shape with all elements set to one.

torch.arange(): Returns a 1-D tensor with values from start to end-1 with a specified step size. Similar to the Python built-in range(), but returns a tensor instead of a list.

torch.linspace(): Returns a 1-D tensor with steps equally spaced values between start and end (inclusive). Unlike torch.arange(), you specify the number of steps rather than the step size.

torch.eye(): Creates an identity tensor of size n x n, where the diagonal elements are ones, and all other elements are zeros. Useful for creating identity matrices used in linear algebra operations.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [26]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
